# Generated by Django 3.2.13 on 2022-06-14 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notlar',
            name='tarih',
            field=models.DateField(default=datetime.date(2022, 6, 14)),
        ),
    ]
