# Generated by Django 3.2.13 on 2022-06-15 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0002_notlar_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notlar',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
